yarn.lock

fix-mem-security-issue

---

src/components/article-detail.component.js

- [ 84 ] Include Jira Ticket No. in Title

nep-84-redesign-article-detail: article page redesing

---

src/components/article-webview.component.js

- [89 ] Include Jira Ticket No. in Title

nep-89-webview-loading: webview loading is shown

---

app.js
src/components/offline-notification.component.js
src/components/splash-screen.component.js
src/frame/app-container.js
src/lang/np.js
src/screens/navigation/bottom-navigation.screen.js

- [78 ] Include Jira Ticket No. in Title

nep-78-refresh-btn: refresh btn in splash screen when internet is off

---

src/components/article-webview.component.js

- [ 91] Include Jira Ticket No. in Title

nep-91-increase-webview-loader: spiner added for webview

---

src/components/article-card.component.js
src/components/article-detail.component.js
src/components/index.js
src/components/time.component.js
src/components/twitter-card.component.js

- [94 ] Include Jira Ticket No. in Title

Nep 94 time component

---

src/components/article-detail.component.js

- [96 ] Include Jira Ticket No. in Title

nep-96-bug-app-crash: resolved issues for app crash when content is null

---

app.js
schema.graphql
src/mutations/__generated__/storeFcmMutation.graphql.js
src/mutations/store-fcm.mutation.js

nep-13-add-timezone: timezone is added to the store mutation

---

src/screens/headline-screen/headline.screen.js

- removed politics section as already merged that one with news section

merge-article-news-politics: 

---

.eslintignore
.prettierignore
app.js
package.json
src/components/article-webview.component.js
src/components/offline-notification.component.js
src/components/splash-screen.component.js
src/components/time.component.js
src/components/twitter-card.component.js
src/error/error-boundry.js
src/frame/app-layout.js
src/screens/headline-screen/headline.screen.js
src/style.js
src/styled.js
yarn.lock

 NEP-147/Remove native-base library

---

src/layout/article/article-list/article-list.component.js
src/layout/headline/tab-view/headline-list.component.js
src/layout/twitter/twitter-list.component.js

NEP-146: refresh conrtol icon color changed

---

.vscode/settings.json
android/app/src/main/AndroidManifest.xml
global.js
package.json
src/components/weather.component.js
src/frame/app-layout.js
src/helper/dateConverter.js
src/helper/dateFormatter.js
src/helper/time.js
src/helper/utils.js
src/screens/home-screen/home.screen.js
yarn.lock

@syuraj  @shrestha2lt8  sir.. please review here

W9 add date weather to header

---

src/frame/app-layout.js

w9-scroll view issue

---

src/helper/dateConverter.js

@syuraj  sir unused functions removed

w9-removed unused functions

---

.github/workflows/android-publish.yml

Copying some changes from master to release

---

.env
.env.release
README.md
android/app/build.gradle
android/app/google-services.json
android/app/src/main/res/values/strings.xml
appcenter-pre-build.sh
babel.config.js
package.json
src/environment.js
src/screens/home-screen/home.screen.js
yarn.lock

using react-native-dotenv to store diff  env varibles for diff env

---

appcenter-pre-build.sh

hot-fix: typo fix

---

src/layout/twitter/twitter-list-item.component.js
src/layout/twitter/twitter-list.component.js

Twitter screen ui styling

---

.prettierrc
schema.graphql
src/screens/corona-stats-screen/__generated__/coronaStatsScreenQuery.graphql.js
src/screens/corona-stats-screen/components/metric.component.js
src/screens/corona-stats-screen/components/stats.card.js
src/screens/corona-stats-screen/components/stats.list.js
src/screens/corona-stats-screen/index.js
src/screens/navigation/bottom-navigation.screen.js
src/screens/twitter-screen/__generated__/twitterScreenQuery.graphql.js

Corona stats screen

---

README.md
package.json
src/layout/article/article-detail/article-detail.component.tsx

- simplying yarn scripts commands

NEP-172- Add Share button on Article Detail Screen

---

android/app/src/main/AndroidManifest.xml
appcenter-pre-build.sh
prepare_release.sh

Release 05 25 -merge to master

---

src/layout/article/article-list/article-list.component.js
src/layout/headline/tab-view/headline-list.component.js
src/layout/twitter/twitter-list.component.js

NEP-182 : fixed on click the bottom tab scroll to top

---

app.js
src/graphql/graphql-client.js
src/layout/article/article-detail/article-detail.component.tsx
src/layout/article/article-list/article-list.component.js
src/layout/headline/tab-view/headline-list.component.js
src/layout/twitter/twitter-list.component.js
src/services/navigationService.js
src/services/notification-handler.js

NEP-184 : Notification click done and comments removed

---

app.js
package.json
src/helper/realm.js
src/screens/headline-screen/headline.screen.js
src/screens/home-screen/home.screen.js

NEP-107 : mongo realm set on home and headline screens

---

app.js
package-lock.json
package.json
src/helper/cacheStorage.js
src/screens/headline-screen/headline.screen.js
src/screens/home-screen/home.screen.js

NEP-107 : Async storage on home and headline screen

---

package-lock.json
package.json
src/layout/article/article-detail/article-detail.container.tsx
src/layout/article/article-list/article-list-container.component.js
src/layout/article/article-list/article-list.component.js
src/layout/headline/tab-view/headline-list.container.js

NEP-169 : View pager branch

---

app.js
src/layout/article/article-detail/article-detail.container.tsx

NEP-169 : Article sliced upto 11 articles, 5 left and 5 right

---

package.json
src/layout/article/article-list/article-list-item.component.js
src/screens/headline-screen/headline.screen.js

swiping category issue fixed

---

src/screens/corona-screen/corona.screen.js
src/screens/corona-screen/coronaCountryStats/countryCard.js
src/screens/corona-screen/coronaCountryStats/countryList.js
src/screens/navigation/bottom-navigation.screen.js

NEP-203: Old corona screen revived

---

src/graphql/graphql-client.js
src/screens/corona-screen/corona.screen.js
src/screens/corona-screen/coronaDistrictStats/coronaSummary.js
src/screens/corona-screen/coronaDistrictStats/districtCard.js
src/screens/corona-screen/coronaDistrictStats/districtList.js

NEP-205 : Corona district info

---

src/graphql/graphql-client.js
src/screens/corona-screen/corona.screen.js
src/screens/corona-screen/coronaCountryStats/countryCard.js
src/screens/corona-screen/coronaCountryStats/countryList.js
src/screens/corona-screen/coronaDistrictStats/coronaSummary.js
src/screens/corona-screen/coronaDistrictStats/districtList.js

NEP-204 : Corona world branch

---

android/app/src/main/AndroidManifest.xml

NEP-210 : App reloading from background issue

---

src/screens/headline-screen/headline.screen.js
src/screens/home-screen/home.screen.js

NEP-215 : article refreshing issue solved

---

android/app/src/main/AndroidManifest.xml
app.js
src/frame/app-container.js
src/screens/navigation/corona-bottom-navigation.screen.js

NEP-213 : Corona notif click redirected to corona screen

---

src/screens/trending-screen/components/trendingCard.js
src/screens/trending-screen/components/trendingListContainer.js
src/screens/trending-screen/trending.screen.js

NEP-216 : all trendigs shown

---

src/screens/headline-screen/headline.screen.js
src/screens/home-screen/home.screen.js

news refreshing minor error

---

src/layout/twitter/twitter-list-item.component.js
src/screens/headline-screen/headline.screen.js
src/screens/home-screen/home.screen.js
src/screens/twitter-screen/twitter.screen.js

News refresh issue

---

src/layout/article/article-detail/article-detail.component.tsx
src/screens/home-screen/home.screen.js
src/screens/trending-screen/components/trendingCard.js
src/screens/trending-screen/components/trendingDetail.js
src/screens/trending-screen/components/trendingListContainer.js

-   [x] Write Unit Tests
-   [x] Add screenshots whenever possible

NEP-223 : trending detail page added

---

src/ducks/sagas.js
src/layout/article/article-list/article-list-item.component.js
src/screens/headline-screen/headline.screen.js
src/services/notification-handler.js

few date issues

---

src/screens/corona-screen/coronaCountryStats/countryList.js
src/screens/corona-screen/coronaDistrictStats/districtList.js
src/screens/twitter-screen/twitter.screen.js

error handling done

---

src/helper/text.js
src/lang/en.js
src/lang/np.js
src/screens/corona-screen/coronaCountryStats/countryList.js
src/screens/corona-screen/coronaDistrictStats/districtList.js
src/screens/headline-screen/headline.screen.js
src/screens/twitter-screen/twitter.screen.js

NEP-211, 220, 226, 231 : New category added

---

src/layout/article/article-detail/article-detail.component.tsx
src/screens/headline-screen/headline.screen.js
src/screens/home-screen/home.screen.js

 NEP-242  :  Hash tag added

---

src/helper/text.js
src/lang/en.js
src/lang/np.js
src/layout/article/article-detail/article-detail.component.tsx
src/screens/headline-screen/headline.screen.js
src/screens/home-screen/home.screen.js

NEP:258 - Merge समाज and बिचार category into single category समाज

---

src/screens/corona-screen/coronaDistrictStats/districtList.js

NEP-260 : corona source added

---

src/components/article-webview.component.js
src/screens/corona-screen/coronaCountryStats/countryList.js
src/screens/corona-screen/coronaDistrictStats/districtList.js

NEP-237 : Corona source

---

src/helper/cacheStorage.js

NEP-263 : store to local storage only when article is present

---

src/screens/trending-screen/components/trendingDetail.js

twitter @ removed from app

---

src/layout/article/article-detail/article-detail.component.tsx

NEP-268 : play store link share

---

src/layout/article/article-list/article-list-item.component.js

NEP-270 : Article margin reduced

---

android/app/src/main/AndroidManifest.xml
src/screens/radio-screen/components/bottomPlayer.js
src/screens/radio-screen/components/radioCard.js
src/screens/radio-screen/components/radioListContainer.js
src/screens/radio-screen/radio.screen.js

NEP-269 : Fm radio prod

---

src/helper/text.js
src/lang/en.js
src/lang/np.js
src/layout/article/article-list/article-list-item.component.js
src/screens/headline-screen/headline.screen.js
src/screens/home-screen/home.screen.js

NEP-254 : new cartoon category added

---

src/layout/article/article-detail/article-detail.component.tsx
src/layout/article/article-list/article-list-item.component.js

NEP-254 : cartoon article detail modified

---

src/screens/radio-screen/radio.screen.js

NEP-269 : fetched Fm list from backend

---

src/screens/radio-screen/components/bottomPlayer.js

radio name added

---

src/screens/corona-screen/coronaDistrictStats/districtCard.js
src/screens/corona-screen/coronaDistrictStats/districtList.js

NEP-278 : New cases added to districts

---

src/services/asyncStorageService.js

Minor lgtm error

---

app.js
src/layout/article/article-list/article-list-item.component.js
src/layout/headline/tab-view/headline-list.component.js
src/screens/home-screen/components/article-list/article-list.component.js
src/screens/home-screen/components/article-list/article.component.js

NEP-4 : Read article background blurred slightly

---

app.js
src/graphql/graphql-client.js
src/layout/article/article-detail/article-detail.container.tsx
src/services/asyncStorageService.js

NEP-4 : Read articles stored to mobile cache only for 5 days

---

src/helper/cacheStorage.js
src/screens/headline-screen/headline.screen.js

NEP-293 : Caching articles in category page

---

src/screens/corona-screen/coronaCountryStats/countryCard.js
src/screens/corona-screen/coronaCountryStats/countryList.js
src/screens/corona-screen/coronaDistrictStats/coronaSummary.js
src/screens/corona-screen/coronaDistrictStats/districtCard.js
src/screens/corona-screen/coronaDistrictStats/districtList.js

NEP-295 : Corona Page Redesign

---

src/screens/trending-screen/trending-tabs/trending-persons/components/trendingListContainer.js

Remove unused imports

---

.detoxrc.json
.github/workflows/android-detox-test.yml
e2e/firstTest.e2e.js
src/screens/trending-screen/trending-tabs/index.js

detox testing for new Ui added

---

package.json
src/screens/home-screen/components/storyHeadline/roundStory.js
src/screens/home-screen/components/storyHeadline/storyHeadline.js
src/screens/home-screen/components/storyHeadline/swiperStory.js
src/screens/home-screen/home.screen.js
yarn.lock

Nep 192 instagram like story

---

src/screens/home-screen/components/weather.component.js

NEP-187 : Temperature icon

---

src/helper/dateFormatter.js
src/screens/home-screen/components/nepaliEvent.component.js
src/screens/home-screen/home.screen.js

NEP-256 : Added nepali event in home page

---

src/screens/home-screen/components/nepaliEvent.component.js

NEP-256 : removed -- when event doesn't exist

---

src/screens/home-screen/components/storyHeadline/roundStory.js
src/screens/home-screen/components/storyHeadline/storyHeadline.js
src/screens/home-screen/components/storyHeadline/storyStorageservices.js
src/screens/home-screen/components/storyHeadline/swiperStory.js

NEP-192 : sorted stories on the basis of read and unread

---

src/screens/home-screen/home.screen.js

Home refreshing issue tried to fix

---

src/screens/home-screen/home.screen.js

Home refresh issue

---

src/layout/article/article-detail/article-detail.component.tsx
src/screens/home-screen/components/article-list/article-list-container.component.js
src/screens/home-screen/components/article-list/article-list.component.js
src/screens/home-screen/components/article-list/article.component.js
src/screens/home-screen/components/article-list/showMoreModal.js
src/screens/home-screen/home.screen.js
src/services/newsLike.services.js

NEP-225 : news like

---

src/screens/corona-screen/coronaCountryStats/country.test.js
src/screens/corona-screen/coronaDistrictStats/district.test.js
src/screens/radio-screen/components/radio.test.js
src/screens/trending-screen/trending-tabs/trending-persons/components/trendingCard.test.js

Test case for static components added

---

app.js
src/layout/article/article-detail/article-detail.component.tsx
src/layout/article/article-detail/article-detail.container.tsx
src/layout/headline/tab-view/headline-list.container.js

Notification issue solved

---

src/screens/trending-screen/trending-detail/index.js
src/screens/trending-screen/trending-detail/trendingNewsDetail.js
src/screens/trending-screen/trending-detail/trendingTweetDetail.js

removing samachar tab of trending person if no news is present

---

index.js
src/screens/home-screen/components/storyHeadline/storyHeadline.js
src/screens/home-screen/components/storyHeadline/swiperStory.js
src/services/asyncStorageService.js

NEP-304 : story wrong issue and dark mode preserve issue fixed

---

src/screens/radio-screen/components/radioCard.js
src/screens/radio-screen/radio.screen.js

Fm api integrated

---

src/screens/home-screen/components/storyHeadline/swiperStory.js

NEP-308 : Unreadable detail story issue

---

src/layout/article/article-detail/article-detail.component.tsx

NEP-329 : back button for notification

---

src/screens/home-screen/components/storyHeadline/storyHeadline.js
src/screens/home-screen/components/storyHeadline/storyStorageservices.js
src/screens/home-screen/components/storyHeadline/swiperStory.js

NEP-336 : Swipe feature

---

src/screens/settings-screen/settings.screen.js

NEP-319 :  app sharing added

---

src/screens/home-screen/home.screen.js

Weather not visible issue fixed

---

package.json
yarn.lock

NEP-330 : Request animation frame firebase error

---

src/frame/app-container.js
src/layout/article/article-detail/article-detail.container.tsx
src/screens/home-screen/home.screen.js

Nep 339 wrong article temp fix

---

src/services/readArticles.service.js

NEP-350 : Date added to read article

---

app.js
src/frame/app-container.js
src/layout/article/article-detail/article-detail.component.tsx
src/layout/article/article-detail/article-detail.container.tsx
src/layout/article/article-list/article-list-container.component.js
src/layout/headline/tab-view/headline-list.container.js
src/screens/home-screen/home.screen.js
src/screens/navigation/bottom-navigation.screen.js
src/services/readArticles.service.js

Nep 344 notification issue
